version: "3.9"
services:
    mysql:
        image: mariadb:10.8.3
        # Uncomment below when on Mac M1
        # platform: linux/arm64/v8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "{$MYSQL_ROOT_PASSWORD}"
        ports:
            - 3308:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    mailhog:
        image: mailhog/mailhog
        container_name: "mailhog"
        ports:
            - "1025:1025"
            - "8025:8025"
